# Generated by Django 5.1.7 on 2025-03-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSA_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
