# Generated by Django 5.1.7 on 2025-04-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSA_app', '0003_property_property_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CSA_app.property'),
        ),
    ]
