# Generated by Django 5.1.7 on 2025-04-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSA_app', '0004_alter_interaction_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSA_app.property'),
        ),
    ]
