# Generated by Django 5.1.7 on 2025-04-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CSA_app", "0005_alter_interaction_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="image",
            field=models.ImageField(
                default="property_images/default.jpg", upload_to="property_images/"
            ),
        ),
    ]
